
POST http://localhost:3000/create-index
Content-Type: application/json

###
POST http://localhost:3000/store-embeddings
Content-Type: application/json

{
  "text": "Title: Unstoppable (2010)\nRated: PG-13\nRuntime: 98 min\nGenre: Action, Thriller\nActors: Denzel Washington, Chris Pine, Rosario Dawson\nPlot: With an unmanned, half-mile-long freight train barreling toward a city, a veteran engineer and a young conductor race against the clock to prevent a catastrophe.",
  "metadata": {
    "name": "Unstoppable",
    "year": 2010,
    "actors": "Denzel Washington, Chris Pine, Rosario Dawson",
    "genre": "Action, Thriller"
  }
}

# {
#   "text": "Title: Crazy AI (2025)\nRated: PG-13\nRuntime: 98 min\nGenre: Action, Thriller\nActors: Dilum Darshana\nPlot: With an unmanned, half-mile-long freight train barreling toward a city, a veteran engineer and a young conductor race against the clock to prevent a catastrophe.",
#   "metadata": {
#     "name": "Crazy AI",
#     "year": 2025,
#     "actors": "Dilum Darshana",
#     "genre": "Action, Thriller"
#   }
# }

###
POST http://localhost:3000/query
Content-Type: application/json

{ 
  "query": "What movies released in year 2025?"
}

###
GET http://localhost:3000/index/idx:movies_json

###
POST http://localhost:3000/records
Content-Type: application/json

{ 
  "index": "idx:movies_json"
}

###
POST http://localhost:3000/chat
Content-Type: application/json

{ 
  "query": "What is the movie featured by Dilum?"
}