
POST http://localhost:4000/create-index
Content-Type: application/json

###
POST http://localhost:4000/store-embeddings
Content-Type: application/json

{
    "text": "Unstoppable is a 2010 action-thriller film starring Denzel Washington, Chris Pine, and Rosario Dawson. Rated PG-13 with a runtime of 98 minutes, it follows a veteran engineer and a young conductor racing against time to stop an unmanned freight train heading toward a city.",
    "metadata": {
      "name": "Unstoppable",
      "year": 2010,
      "actors": "Denzel Washington, Chris Pine, Rosario Dawson",
      "genre": "Action, Thriller"
    }
  }

###
POST http://localhost:4000/query
Content-Type: application/json

{ 
  "query": "A film released in the year 2010"
}

###
GET http://localhost:4000/index/idx:faq_vector

###
POST http://localhost:3000/records
Content-Type: application/json

{ 
  "index": "idx:movies_json"
}

###
POST http://localhost:4000/flush-db
Content-Type: application/json


###
POST http://localhost:3000/chat
Content-Type: application/json

{ 
  "query": "In which year was Forrest Gump released?"
}