allowBuilds:
  '@biomejs/biome': true
  '@modelcontextprotocol/ext-apps': false
  '@modelcontextprotocol/inspector': true
  '@prisma/client': true
  '@prisma/engines': true
  cpu-features: false
  esbuild: true
  kerberos: false
  macos-export-certificate-and-key: false
  mongodb-client-encryption: false
  onnxruntime-node: true
  os-dns-native: false
  prisma: true
  protobufjs: true
  sharp: true
  simple-git-hooks: true
  ssh2: false

minimumReleaseAgeExclude:
  - uuid@14.0.1
  - '@langchain/openai@1.5.10'

packages:
  - 'langchain'
  - 'guardrails'
  - 'chromadb'
  - 'rag-json'
  - 'rag-huggingface'
  - 'langgraph'
  - 'mcp-client'
  - 'mcp-server-mongo'
  - 'mcp-server-mongo-v2'
  - 'rag-redis'
  - 'rag-graph'
  - 'rag-hybrid'
  - 'voltagent'
  - '*'
